# 3/28
1. Measure the unique features across individual
2. Matching: tell how many people are hit by RNG fields (most informative0, divided by the total number of records
3. How much information do we really need to idenfit individuals --> So far we only know some features that are informative.  Next step is how much we need to know to uniqely identify an individual
4. Step through 1 RNG reading, then try 2, etc. we should show higher uniquessness in the data as we increase the number of readings
5. Need to understand how we design the test set for the patients linking.  Should also include some patients that were not in the original dataset in order to determine the precision of said target matching.
6. Said I was on the right path but trying reidentifaction this early was too much

> **Conclusion From Previous Notebook:** The highest values are 0.289, 0.273, and 0.266, for the following fields, respectively: 'FairlyActiveMinutes', 'VeryActiveDistance', and 'LightlyActiveMinutes'.  Calories and total steps were both relatively uninformative.

## Goals
1. Assume to conduct the uniqueness analysis on each activity separately. In other words, we compute a uniqueness score, for each activity. Here, we can start by considering the top-3 activity that you have already identified using the KL-divergence.
2. Consider a threshold value to match the reading

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [34]:
################## DATA FRAME ##################
datafile = 'Data/Fitbit_Kaggle/dailyActivity_merged.csv'
fields = ['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance', 
          'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 'SedentaryActiveDistance', 
          'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories']

pd.set_option('display.max_rows', 100)
df = pd.read_csv(datafile, skipinitialspace=True, usecols=fields)
n_rows, n_cols = df.shape
df = df.loc[:, ["Id", "FairlyActiveMinutes", "VeryActiveDistance", "LightlyActiveMinutes"]]
display(df.head(32))

            Id  FairlyActiveMinutes  VeryActiveDistance  LightlyActiveMinutes
0   1503960366                   13                1.88                   328
1   1503960366                   19                1.57                   217
2   1503960366                   11                2.44                   181
3   1503960366                   34                2.14                   209
4   1503960366                   10                2.71                   221
5   1503960366                   20                3.19                   164
6   1503960366                   16                3.25                   233
7   1503960366                   31                3.53                   264
8   1503960366                   12                1.96                   205
9   1503960366                    8                1.34                   211
10  1503960366                   27                4.76                   130
11  1503960366                   21                2.81                   262
12  1503960366                    5                2.92                   238
13  1503960366                   14                5.29                   216
14  1503960366                   23                2.33                   279
15  1503960366                   11                6.40                   243
16  1503960366                   28                3.54                   189
17  1503960366                   12                1.06                   243
18  1503960366                   34                3.56                   217
19  1503960366                   35                2.29                   246
20  1503960366                   15                3.21                   277
21  1503960366                   24                3.73                   254
22  1503960366                   22                2.46                   203
23  1503960366                   24                2.92                   250
24  1503960366                    6                1.97                   289
25  1503960366                   46                2.46                   175
26  1503960366                    8                3.53                   203
27  1503960366                   11                3.45                   206
28  1503960366                   31                3.35                   214
29  1503960366                   23                2.56                   251
30  1503960366                    0                0.00                     0
31  1624580081                    0                0.00                   146

In [35]:
# 30 measurements for most individuals
x = 1 #random.randint(1, 10000)

max_fam = max(df.loc[:, "FairlyActiveMinutes"])
min_fam = min(df.loc[:, "FairlyActiveMinutes"])

x_fam = [0]*x
for i in range(x):
    x_fam[i] = random.randint(min_fam, max_fam)

In [36]:
all_IDs = set(df.loc[:, "Id"])
occurence_dict = dict(zip(all_IDs, [0]*len(all_IDs)))

In [37]:
# for thresh in range(1,6)
thresh = 1

thresh_vec = [0] * (2*thresh+1)
for i, val in enumerate(thresh_vec):
    thresh_vec[i] = i - thresh
thresh_vec

[-1, 0, 1]

In [38]:
occurence_matrix = np.zeros((n_rows, len(thresh_vec)))

for i, thresh_val in enumerate(thresh_vec):
    for j in range(n_rows):
        for xfam_val in x_fam: 
            if (df.iloc[j,1]-xfam_val < thresh_val):
                occurence_matrix[j, i] += 1

In [ ]:
'''
for i in range(n_rows):
    if df.iloc[i,1] in x_fam:
        occurence_dict[df.iloc[i,0]] += 1
        
for i in range(n_rows):
    for xfam_val in x_fam:
        if (df.iloc[i,1]-xfam_val < thresh):
            occurence_dict[df.iloc[i,0]] += 1

for i in range(n_rows):
    # CANT USE i BECAUSE ITS SIZE x (30ish)
    if (df.iloc[i,1]-xfam_val[] < thresh):
        occurence_dict[df.iloc[i,0]] += 1

unique_list = [0]*len(all_IDs)
for i, key in enumerate(all_IDs):
    if occurence_dict[key] > x:
        unique_list[i] = 1

uniqueness_dict = dict(zip(all_IDs, unique_list))
'''

In [23]:
x

9071